aadesaed/cat/app/App.class: aadesaed/cat/app/App.java
	@printf "Building the App.\n"
	javac -cp . aadesaed/cat/app/App.java
	@printf "Done.\n"

run: aadesaed/cat/app/App.class
	java aadesaed.cat.app.App
