build: aadesaed/cat/app/App.java
	@printf "Building classes.\n"
	javac -cp .:../lib/apache-commons-cli.jar aadesaed/cat/app/App.java
	@printf "Done.\n"

run: aadesaed/cat/app/App.class
	java aadesaed.cat.app.App
